import { GoogleGenAI, Modality } from "@google/genai";
import type { FileInfo } from '../types';

if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const base64ToInlineData = (fileInfo: FileInfo) => {
    const [header, data] = fileInfo.base64.split(',');
    if (!header || !data) {
        throw new Error("Invalid base64 string format");
    }
    const mimeType = header.match(/:(.*?);/)?.[1] ?? fileInfo.type;
    return {
        inlineData: {
            mimeType,
            data,
        },
    };
};

export const extractVehicle = async (
    subjectVehicle: FileInfo,
): Promise<string> => {
    const model = 'gemini-2.5-flash-image';
    
    const subjectVehiclePart = base64ToInlineData(subjectVehicle);

    const prompt = `
**TASK: PRECISION VEHICLE EXTRACTION**

Your task is to perform a clean and precise extraction of the main vehicle from the provided image.

**INSTRUCTIONS:**
1.  **IDENTIFY:** Accurately identify the primary subject vehicle in the image.
2.  **MASK:** Create a highly detailed mask that perfectly outlines the vehicle, including windows and gaps between spokes on the wheels. Exclude everything else (background, ground, other objects, shadows).
3.  **REMOVE BACKGROUND:** Use the mask to completely remove the background, making it 100% transparent.
4.  **CROP TIGHTLY:** Crop the resulting image so that the image dimensions are as small as possible while still containing the entire vehicle. There should be minimal transparent padding around the vehicle. The vehicle should be the only thing in the image.

The final output **MUST** be a PNG image of **ONLY** the vehicle on a fully transparent background, cropped to its bounds.
`;

    const response = await ai.models.generateContent({
        model,
        contents: {
            parts: [
                { text: prompt },
                subjectVehiclePart,
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    const parts = response?.candidates?.[0]?.content?.parts;
    if (parts) {
        for (const part of parts) {
            if (part.inlineData) {
                const base64ImageBytes: string = part.inlineData.data;
                return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
            }
        }
    }

    throw new Error("No image was generated by the API during extraction.");
};


export const blendVehicleIntoScene = async (
    compositeImage: FileInfo
): Promise<string> => {
    const model = 'gemini-2.5-flash-image';
    const imagePart = base64ToInlineData(compositeImage);

    const prompt = `
**TASK: REALISTIC VEHICLE INTEGRATION**

You are a master photo editor specializing in photorealistic compositing. You will be provided with a single composite image containing a background scene with a vehicle placed on top of it.

**YOUR SOLE OBJECTIVE:** Make the vehicle look like it naturally belongs in the background scene by realistically blending it.

**MANDATORY RULES:**
1.  **PRESERVE THE BACKGROUND:** The background scene within the provided image is **PERFECT** and **MUST NOT BE ALTERED, REPLACED, OR MODIFIED IN ANY WAY.**
2.  **PRESERVE VEHICLE PLACEMENT:** The vehicle's position, size, and orientation are **FIXED** and **MUST NOT BE CHANGED.**

**YOUR ONLY ALLOWED ACTIONS:**
- **APPLY REALISTIC LIGHTING:** Adjust the lighting on the vehicle to match the direction, color, and intensity of the light sources in the background.
- **CAST ACCURATE SHADOWS:** Generate a soft, realistic shadow on the ground beneath and around the vehicle, consistent with the scene's lighting.
- **ADD ENVIRONMENT REFLECTIONS:** Apply subtle reflections of the surrounding environment onto the vehicle's reflective surfaces (e.g., windows, paint, chrome).

The final output MUST be the original image, but with the vehicle seamlessly blended. Return ONLY the final photorealistic image.
`;

    const response = await ai.models.generateContent({
        model,
        contents: {
            parts: [{ text: prompt }, imagePart],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    const parts = response?.candidates?.[0]?.content?.parts;
    if (parts) {
        for (const part of parts) {
            if (part.inlineData) {
                const base64ImageBytes: string = part.inlineData.data;
                return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
            }
        }
    }

    throw new Error("No image was generated by the API during blending.");
};